---
title: Loke Carlsson
contact: Kontakt
email: lc222ak@student.lnu.se
description: |
  Presentation av Loke Carlsson, studerande webbprogrammerare vid Linneuniversitetet, Kalmar.
baseurl: ''
url: http://yourdomain.com
twitter_username: Loke_Carlsson
github_username: LokeCarlsson
facebook_username: loke.carlsson.1
markdown: kramdown
timezone: Europe/Stockholm
